# Generated by Django 5.1.1 on 2024-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
