# Generated by Django 5.1.1 on 2024-10-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
