# Generated by Django 5.1.1 on 2024-10-05 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="viewed_by",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_profiles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="down_payment",
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="duration",
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="installment_payment_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Credit Success"),
                    ("D", "Debit Success"),
                    ("F", "Failed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
