# Generated by Django 5.1.1 on 2024-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_property_is_active_companyview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Credit Success"),
                    ("D", "Debit Success"),
                    ("F", "Failed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
